version: "3.7"

services:
  app:
    image: portto-api:1.0-alpine
    ports:
      - 3000:3000
    depends_on:
      - mysql
    entrypoint: /go/bin/server
    command: --sqlHost=mysql
    networks:
      - portto
  indexer:
    image: portto-indexer:1.0-alpine
    depends_on:
      - mysql
    entrypoint: /go/bin/main
    command: --sqlHost=mysql --worker=10
    networks:
      - portto

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: portto
      MYSQL_DATABASE: portto
    networks:
      - portto

volumes:
  mysql-data:
   
networks:
  portto:
    driver: bridge